### PR TITLE
Development of Capstone project - PR to main

### PR DESCRIPTION
**Pull request by mullenlucas**
This project was made between 2 participants

## Implemented features:

- Made an html skeleton with a section to be populated via JavaScript. The HTML consists of the header, the main section of cards, and the footer, as well as the pop-up for the comments
- The cards are generated with JavaScript fetching information from the TV-Series API.
- The cards contain a heart icon for the like functionality. The series liked by the user are stored in the local storage, so when the user likes a series, that information is saved, and the icon is updated. This functionality sends a POST request to the involvement API for storing the likes.
- Also the cards contain a comment button that displays the pop-up, where the user can make comments on the series. These comments are sent through a POST request to the involvement API.
- Counter functions where implemented to store the amount of items and the amount of comments
- These functions were provided a test for their functionality

All these tasks were organized and implemented daily with the following kanban board: https://github.com/users/mullenlucas/projects/3

Also a video showcasing the developed website was recorded, found on the following link: https://drive.google.com/file/d/1wqJsJLr6ACOs4LNcAcYGJxerSDgixzQf/view?usp=sharing

### CODE REVIEW

**Review by Mihndim2020 — CHANGES_REQUESTED** [review]
### Hi Team, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark: Correct use of Gitflow. 
:heavy_check_mark: No `Linter` errors
:heavy_check_mark: Descriptive `PR` summary,
:heavy_check_mark: Great job with UI,
:heavy_check_mark: Highly Clean/Organized code,
:heavy_check_mark: Good commit messages,
:heavy_check_mark: Descriptive Readme file.
:heavy_check_mark: Great job with test coverage

There are some issues that you still need to work on to get this project approved, but you are almost there!
ALMOST-MINION

# Status: Requires Changes ♻️
_Check the comments under the review._

- [x] As it is a [requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/js_capstone.md) for this project, " `You all should appear in the video and talk about the project.` ", please ensure all the members in the video should appear in the video and talk about the project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mullenlucas** [comment]
Hello @Mihndim2020 !

Thank you very much for your comments and encouragements !

We are concerned about the review since we understand that both of the team members, me and Efiamotu, appear in the linked video and we both speak in said video. For this project we are only 2 members. We would like to ask a revision of the linked video:
https://drive.google.com/file/d/1wqJsJLr6ACOs4LNcAcYGJxerSDgixzQf/view?usp=sharing

Thank you !

**Comment by mullenlucas** [comment]
Hello, thank you for the comments and encouragements!

It seems only one of the participants was being shown in the video.

We recorded a new video making sure we both appear, and updated the readme to include a link to the video, found on the following link:
https://drive.google.com/file/d/1TV6W07lS4zedpbGU_WjFpsNSohtWaP9g/view?usp=sharing

Thank you for the review !

**Review by mugishasam123 — APPROVED** [review]
Hi team 👋 , 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
